[package]
edition.workspace = true
license.workspace = true
name = "motyga-utils-output-truncation"
version.workspace = true

[lints]
workspace = true

[dependencies]
motyga-protocol = { workspace = true }
motyga-utils-string = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lib]
doctest = false
