[package]
name = "motyga-utils-sandbox-summary"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
motyga-core = { workspace = true }
motyga-model-provider-info = { workspace = true }
motyga-protocol = { workspace = true }
motyga-utils-absolute-path = { workspace = true }

[dev-dependencies]
motyga-utils-absolute-path = { workspace = true }
pretty_assertions = { workspace = true }

[lib]
doctest = false
