[package]
name = "motyga-chatgpt"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
motyga-connectors = { workspace = true }
motyga-core = { workspace = true }
motyga-git-utils = { workspace = true }
motyga-login = { workspace = true }
motyga-model-provider = { workspace = true }
motyga-plugin = { workspace = true }
motyga-utils-cli = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
motyga-utils-cargo-bin = { workspace = true }
pretty_assertions = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }

[lib]
doctest = false
