// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One distributor that can serve a model: an opaque routing token plus the name to show for it.
 * Address it by sending `<model>@<id>`; `label` is display-only.
 */
export type ModelProvider = { id: string, label: string, };
