// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Model } from "./Model";

export type ModelListResponse = { data: Array<Model>,
/**
 * Opaque cursor to pass to the next call to continue after the last item.
 * If None, there are no more items to return.
 */
nextCursor: string | null,
/**
 * Why the last catalog refresh failed, when `data` is therefore the bundled fallback rather
 * than the provider's catalog. A rejected key or an unreachable gateway used to be invisible
 * here: the list simply came back short, and the client had no way to tell a small catalog
 * from a failed refresh.
 */
catalogRefreshError: string | null, };
