[package]
edition.workspace = true
license.workspace = true
name = "motyga-extension-api"
version.workspace = true

[lib]
name = "motyga_extension_api"
path = "src/lib.rs"
test = false
doctest = false

[lints]
workspace = true

[dependencies]
motyga-config = { workspace = true }
motyga-context-fragments = { workspace = true }
motyga-protocol = { workspace = true }
motyga-tools = { workspace = true }
motyga-utils-absolute-path = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
