[package]
edition.workspace = true
license.workspace = true
name = "motyga-core-api"
version.workspace = true

[lib]
doctest = false
name = "motyga_core_api"
path = "src/lib.rs"
test = false

[lints]
workspace = true

[dependencies]
motyga-app-server-protocol = { workspace = true }
motyga-arg0 = { workspace = true }
motyga-analytics = { workspace = true }
motyga-config = { workspace = true }
motyga-core = { workspace = true }
motyga-extension-api = { workspace = true }
motyga-home = { workspace = true }
motyga-exec-server = { workspace = true }
motyga-features = { workspace = true }
motyga-login = { workspace = true }
motyga-model-provider-info = { workspace = true }
motyga-models-manager = { workspace = true }
motyga-protocol = { workspace = true }
motyga-utils-absolute-path = { workspace = true }
