[package]
edition.workspace = true
license.workspace = true
name = "motyga-connectors-extension"
version.workspace = true

[lib]
name = "motyga_connectors_extension"
path = "src/lib.rs"
doctest = false
test = false

[lints]
workspace = true

[dependencies]
motyga-connectors = { workspace = true }
motyga-core-plugins = { workspace = true }
motyga-plugin = { workspace = true }
motyga-utils-path-uri = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
