[package]
edition.workspace = true
license.workspace = true
name = "motyga-features"
version.workspace = true

[lib]
doctest = false
name = "motyga_features"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
motyga-otel = { workspace = true }
motyga-protocol = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
toml = { workspace = true }
tracing = { workspace = true, features = ["log"] }

[dev-dependencies]
pretty_assertions = { workspace = true }
