[package]
edition.workspace = true
license.workspace = true
name = "motyga-prompts"
version.workspace = true

[lib]
doctest = false
name = "motyga_prompts"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
motyga-context-fragments = { workspace = true }
motyga-git-utils = { workspace = true }
motyga-execpolicy = { workspace = true }
motyga-protocol = { workspace = true }
motyga-utils-absolute-path = { workspace = true }
motyga-utils-template = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
