[package]
edition.workspace = true
license.workspace = true
name = "motyga-mcp-extension"
version.workspace = true

[lib]
name = "motyga_mcp_extension"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
motyga-core = { workspace = true }
motyga-core-plugins = { workspace = true }
motyga-config = { workspace = true }
motyga-connectors-extension = { workspace = true }
motyga-exec-server = { workspace = true }
motyga-extension-api = { workspace = true }
motyga-features = { workspace = true }
motyga-mcp = { workspace = true }
motyga-plugin = { workspace = true }
motyga-protocol = { workspace = true }
motyga-utils-absolute-path = { workspace = true }
motyga-utils-path-uri = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["sync"] }

[dev-dependencies]
motyga-login = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
