[package]
edition.workspace = true
license.workspace = true
name = "motyga-analytics"
version.workspace = true

[lib]
doctest = false
name = "motyga_analytics"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
motyga-app-server-protocol = { workspace = true }
motyga-git-utils = { workspace = true }
motyga-login = { workspace = true }
motyga-model-provider = { workspace = true }
motyga-plugin = { workspace = true }
motyga-protocol = { workspace = true }
motyga-state = { workspace = true }
os_info = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha1 = { workspace = true }
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
] }
tracing = { workspace = true, features = ["log"] }

[dev-dependencies]
motyga-utils-absolute-path = { workspace = true }
pretty_assertions = { workspace = true }
