[package]
edition.workspace = true
license.workspace = true
name = "motyga-skills"
version.workspace = true
build = "build.rs"

[lib]
doctest = false
name = "motyga_skills"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
motyga-utils-absolute-path = { workspace = true }
include_dir = { workspace = true }
thiserror = { workspace = true }
