[package]
name = "motyga-exec-server-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "motyga_exec_server_protocol"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
base64 = { workspace = true }
motyga-file-system = { workspace = true }
motyga-network-proxy = { workspace = true }
motyga-protocol = { workspace = true }
motyga-shell-command = { workspace = true }
motyga-utils-path-uri = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
