[package]
name = "motyga-arg0"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "motyga_arg0"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
motyga-apply-patch = { workspace = true }
motyga-exec-server = { workspace = true }
motyga-install-context = { workspace = true }
motyga-linux-sandbox = { workspace = true }
motyga-sandboxing = { workspace = true }
motyga-shell-escalation = { workspace = true }
motyga-utils-absolute-path = { workspace = true }
motyga-utils-home-dir = { workspace = true }
dotenvy = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }

[target.'cfg(windows)'.dependencies]
motyga-windows-sandbox = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
