[package]
edition.workspace = true
license.workspace = true
name = "motyga-tools"
version.workspace = true

[lints]
workspace = true

[dependencies]
motyga-code-mode = { workspace = true }
motyga-connectors = { workspace = true }
motyga-features = { workspace = true }
motyga-file-system = { workspace = true }
motyga-protocol = { workspace = true }
motyga-utils-absolute-path = { workspace = true }
motyga-utils-output-truncation = { workspace = true }
motyga-utils-pty = { workspace = true }
motyga-utils-string = { workspace = true }
jsonptr = { workspace = true }
rmcp = { workspace = true, default-features = false, features = [
    "base64",
    "macros",
    "schemars",
    "server",
] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
urlencoding = { workspace = true }

[dev-dependencies]
motyga-utils-cargo-bin = { workspace = true }
pretty_assertions = { workspace = true }

[lib]
doctest = false
