[package]
edition.workspace = true
license.workspace = true
name = "motyga-web-search-extension"
version.workspace = true

[lib]
name = "motyga_web_search_extension"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
motyga-api = { workspace = true }
motyga-core = { workspace = true }
motyga-extension-api = { workspace = true }
motyga-login = { workspace = true }
motyga-model-provider = { workspace = true }
motyga-model-provider-info = { workspace = true }
motyga-protocol = { workspace = true }
motyga-tools = { workspace = true }
http = { workspace = true }
schemars = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
