[package]
name = "motyga-utils-oss"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
motyga-core = { workspace = true }
motyga-lmstudio = { workspace = true }
motyga-model-provider-info = { workspace = true }
motyga-ollama = { workspace = true }

[lib]
doctest = false
