[package]
edition.workspace = true
license.workspace = true
name = "motyga-plugin"
version.workspace = true

[lib]
doctest = false
name = "motyga_plugin"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
motyga-config = { workspace = true }
motyga-protocol = { workspace = true }
motyga-utils-absolute-path = { workspace = true }
motyga-utils-path-uri = { workspace = true }
motyga-utils-plugins = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
