[package]
edition.workspace = true
license.workspace = true
name = "motyga-guardian"
version.workspace = true

[lib]
name = "motyga_guardian"
path = "src/lib.rs"
test = false
doctest = false

[lints]
workspace = true

[dependencies]
motyga-core = { workspace = true }
motyga-extension-api = { workspace = true }
motyga-protocol = { workspace = true }
