[package]
edition.workspace = true
license.workspace = true
name = "motyga-memories-extension"
version.workspace = true

[lib]
name = "motyga_memories_extension"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
motyga-core = { workspace = true }
motyga-extension-api = { workspace = true }
motyga-features = { workspace = true }
motyga-otel = { workspace = true }
motyga-tools = { workspace = true }
motyga-utils-absolute-path = { workspace = true }
motyga-utils-output-truncation = { workspace = true }
motyga-utils-template = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs"] }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["fs", "macros"] }
